FROM debian:bullseye-backports
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    cmake \
    g++-10 \
    git-core \
    libqt6serialport6 \
    libqt6serialport6-dev \
    qt6-base-dev